### ISSUE TITLE
Modular pkg does not compile

### ISSUE THREAD

**Issue by Morgantiz** [ADVRHumanoids/modular_hhcm#2]
The modular pkg (https://github.com/advrhumanoids/modular_hhcm) cloned inside the container does not compile. 
The last commit also creates a consistency problem with the definition at lines [https://github.com/ADVRHumanoids/concert_description/blob/cf02fb3476e53f71f9422777c70df769c2051d9e/concert_gazebo/launch/modular.launch#L37 https://github.com/ADVRHumanoids/concert_description/blob/cf02fb3476e53f71f9422777c70df769c2051d9e/concert_gazebo/launch/modular.launch#L38](https://github.com/ADVRHumanoids/concert_description/blob/cf02fb3476e53f71f9422777c70df769c2051d9e/concert_gazebo/launch/modular.launch#L37-L38).

**Comment by EdoardoRomiti** [comment]
With commit 5408e1b9ce40f672546da37d1de9aac897c62f4f modular is not a ROS package anymore.
(It was a ROS package before for exposing the meshes, but now we have the package `modular_resources` for that)
There is no **CMakeLists.txt** and **package.xml** anymore so it shouldn't give any more errors when compiling with catkin_make (I managed without errors in a test catkin workspace)
The way to install it's still with `pip install`.
Does this solve the issue?
